plugins {
    id "java-library"
    id "com.github.johnrengelman.shadow" version "6.0.0"
    id "monticore" version "$version"
    id "jacoco"
}

group = "de.monticore.lang"
sourceCompatibility = '11'

def grammarOutDir = "$buildDir/generated-sources/monticore/sourcecode"


sourceSets {
    main.java.srcDirs += [grammarOutDir]

    grammars {
        java.srcDirs = []
        resources {
            srcDirs([grammarDir, grammarOutDir])
            include "**/*.mc4"
        }
    }
}

configurations {grammar}

java {
    registerFeature('grammars') {
        usingSourceSet(sourceSets.grammars)
    }
}

test {
    useJUnitPlatform()
}

dependencies {
    implementation project(':TimeExpressions')
    grammar (project(':TimeExpressions')){
      capabilities {
        requireCapability("de.monticore.expressions:TimeExpressions-grammars")
      }
    }
    implementation project(':BpmnXML')


    implementation "de.monticore.lang:petrinets:$petrinets_version"

    implementation "com.google.guava:guava:$guava_version"
    implementation "com.google.code.gson:gson:$gson_version"
    implementation 'one.util:streamex:0.7.0'
    implementation "org.jgrapht:jgrapht-core:$jgrapht_version"
    implementation "org.jgrapht:jgrapht-io:$jgrapht_version"
    implementation "org.jgrapht:jgrapht-guava:$jgrapht_version"
    implementation "org.zeroturnaround:zt-exec:$exec_version"
    implementation "ch.qos.logback:logback-classic:$logback_version"
    implementation "com.google.code.findbugs:jsr305:$jsr305_version"

    implementation "jakarta.xml.bind:jakarta.xml.bind-api:3.0.1"
    implementation "com.sun.xml.bind:jaxb-core:$jaxb_core_version"
    implementation "com.sun.xml.bind:jaxb-impl:$jaxb_impl_version"
    implementation "com.sun.xml.bind:jaxb-xjc:$jaxb_impl_version"


    /*-----------------------MONTICORE-------------------------------*/
    implementation "de.monticore.lang:ocl:$ocl_version"
    grammar "de.monticore.lang:ocl:$ocl_version:$grammars_classifier"
    implementation "de.monticore.lang:cd4analysis:$mc_version"
    implementation "org.antlr:antlr4-runtime:$antlr_version"
    implementation "de.monticore:monticore-runtime:$mc_version"
    implementation "de.monticore:monticore-grammar:$mc_version"
    grammar "de.monticore:monticore-grammar:$mc_version:$grammars_classifier"

    /*------------------------TESTING-----------------------------------*/
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_jupiter_version"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:$junit_jupiter_version"
    testImplementation "de.monticore:monticore-runtime:$mc_version"
}

task generateWorkflow (type: MCTask) {
    grammar = file "$projectDir/$grammarDir/de/monticore/bpmn/Workflow.mc4"
    outputDir = file "$buildDir/generated-sources/monticore/sourcecode"
    handcodedPath "$projectDir/src/main/java"
    def uptoDate = incCheck("de/monticore/bpmn/Workflow.mc4")
    outputs.upToDateWhen { uptoDate }
}

compileJava.dependsOn(generateWorkflow)

// build sources jar in addition
task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    archiveClassifier = "sources"
}

sourcesJar.dependsOn project.collect { it.tasks.withType(MCTask)}

// build javadoc jar in addition
task javadocJar(type: Jar) {
    from javadoc
    archiveClassifier = "javadoc"
}

// generated java doc contains errors, disable for now
javadoc.failOnError(false)

// build grammar jar as well
task grammarJar(type: Jar) {
    from("$projectDir/src/main/grammars/") { include "**/*.mc4" }
    archiveClassifier = "grammars"
}

task buildAll(type: GradleBuild) {
    tasks = [ 'build' ]
}

defaultTasks 'build'