<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <!-- == PROJECT COORDINATES ============================================= -->

  <parent>
    <groupId>de.monticore.lang</groupId>
    <artifactId>parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <artifactId>workflow</artifactId>

  <properties>
    <monticore.version>5.0.2</monticore.version>
  </properties>

  <!-- == PROJECT META-INFORMATION ======================================== -->

  <name>WorkflowDSL</name>
  <inceptionYear>2019</inceptionYear>

  <organization>
    <name>SE RWTH Aachen</name>
    <url>http://www.se-rwth.de/</url>
  </organization>


  <!-- == DEPENDENCY MANAGEMENT ============================================== -->

  <dependencies>
    <dependency>
      <groupId>de.monticore.lang</groupId>
      <artifactId>ocl</artifactId>
      <version>${ocl.verion}</version>
    </dependency>
    <dependency>
      <groupId>de.monticore.lang</groupId>
      <artifactId>ocl</artifactId>
      <version>${ocl.verion}</version>
      <classifier>${grammars.classifier}</classifier>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>de.monticore.expressions</groupId>
      <artifactId>time</artifactId>
    </dependency>
    <dependency>
      <groupId>de.monticore.expressions</groupId>
      <artifactId>time</artifactId>
      <classifier>${grammars.classifier}</classifier>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>de.monticore.lang</groupId>
      <artifactId>petrinets</artifactId>
    </dependency>
    <dependency>
      <groupId>de.monticore.lang</groupId>
      <artifactId>workflow-xml</artifactId>
    </dependency>
    <dependency>
      <groupId>de.monticore.lang</groupId>
      <artifactId>workflow-xml</artifactId>
      <classifier>schemas</classifier>
    </dependency>

    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
    </dependency>
    <dependency>
      <groupId>one.util</groupId>
      <artifactId>streamex</artifactId>
      <version>0.7.0</version>
    </dependency>
    <dependency>
      <groupId>org.jgrapht</groupId>
      <artifactId>jgrapht-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jgrapht</groupId>
      <artifactId>jgrapht-io</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jgrapht</groupId>
      <artifactId>jgrapht-guava</artifactId>
    </dependency>

    <dependency>
      <groupId>org.zeroturnaround</groupId>
      <artifactId>zt-exec</artifactId>
    </dependency>
<!--    <dependency>
      <groupId>guru.nidi</groupId>
      <artifactId>graphviz-java</artifactId>
    </dependency>-->
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </dependency>


    <!-- drop-in replacement for jaxb, see https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist, https://stackoverflow.com/questions/48204141/replacements-for-deprecated-jpms-modules-with-java-ee-apis -->
    <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sun.xml.bind</groupId>
      <artifactId>jaxb-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sun.xml.bind</groupId>
      <artifactId>jaxb-impl</artifactId>
    </dependency>

    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
    </dependency>

    <!-- MontiCore Dependencies -->
    <dependency>
      <groupId>org.antlr</groupId>
      <artifactId>antlr4-runtime</artifactId>
    </dependency>
    <dependency>
      <groupId>de.monticore</groupId>
      <artifactId>monticore-runtime</artifactId>
      <version>${monticore.version}</version>
    </dependency>
    <dependency>
      <groupId>de.monticore</groupId>
      <artifactId>monticore-grammar</artifactId>
      <version>${monticore.version}</version>
    </dependency>
    <dependency>
      <groupId>de.monticore</groupId>
      <artifactId>monticore-grammar</artifactId>
      <version>${monticore.version}</version>
      <classifier>${grammars.classifier}</classifier>
      <scope>provided</scope>
    </dependency>

    <!-- .. Test Libraries ............................................... -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>de.monticore</groupId>
      <artifactId>monticore-runtime</artifactId>
      <version>${monticore.version}</version>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
  </dependencies>


  <!-- == DEFAULT BUILD SETTINGS =========================================== -->

  <build>
    <extensions>
      <extension>
        <groupId>org.apache.maven.wagon</groupId>
        <artifactId>wagon-webdav-jackrabbit</artifactId>
        <version>${wagon.provider.version}</version>
      </extension>
    </extensions>

    <plugins>
      <plugin>
        <groupId>de.monticore.mojo</groupId>
        <artifactId>monticore-maven-plugin</artifactId>
        <configuration>
          <modelPathDependencies>
            <modelPathDependency>de.monticore.expressions:time</modelPathDependency>
          </modelPathDependencies>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>unpack-schemas</id>
            <goals>
              <goal>unpack-dependencies</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/generated-resources</outputDirectory>
              <includeGroupIds>${project.groupId}</includeGroupIds>
              <includeArtifactIds>workflow-xml</includeArtifactIds>
              <classifier>schemas</classifier>
              <excludeTransitive>true</excludeTransitive>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-resource</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>add-resource</goal>
            </goals>
            <configuration>
              <resources>
                <resource>
                  <directory>${project.build.directory}/generated-resources</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
<!--        <configuration>
          &lt;!&ndash; Exclude generated JAX-B classes from JavaDoc &ndash;&gt;
          <excludePackageNames>org.omg.spec</excludePackageNames>
        </configuration>-->
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <id>docs</id>
            <phase>none</phase> <!-- must be invoked explicitly, not bound to any lifecycle -->
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <appendAssemblyId>false</appendAssemblyId>
              <descriptors>
                <descriptor>src/main/assembly/docs.xml</descriptor>
              </descriptors>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-release-plugin</artifactId>
        <configuration>
          <tagNameFormat>de.monticore.workflow-@{project.version}</tagNameFormat>
        </configuration>
      </plugin>
    </plugins>

  </build>


  <!-- == REPORTING ========================================================== -->

  <reporting>
    <plugins>
      <plugin>
        <groupId>de.monticore.mojo</groupId>
        <artifactId>monticore-maven-plugin</artifactId>
        <inherited>false</inherited>
      </plugin>
    </plugins>
  </reporting>


  <!-- == DISTRIBUTION ==================================================== -->

  <distributionManagement>
    <repository>
      <id>se-nexus</id>
      <url>http://nexus.se.rwth-aachen.de/content/repositories/monticore-releases/</url>
    </repository>
    <snapshotRepository>
      <id>se-nexus</id>
      <url>http://nexus.se.rwth-aachen.de/content/repositories/monticore-snapshots/</url>
    </snapshotRepository>
    <site>
      <id>se-nexus</id>
      <url>dav:http://nexus.se.rwth-aachen.de/content/sites/se-sites/monticore/workflow/${project.version}/</url>
    </site>
  </distributionManagement>

</project>
