image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:7.6.4-jdk11

variables:
  GRADLE_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2"
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - gradle --version
    - gradle build --refresh-dependencies -P mavenPassword=$pass -P mavenUser=$user $GRADLE_OPTS $ARGS1
    
deployToNexus:
  stage: deploy
  needs: [ build ]
  script:
    - gradle --version
    - gradle WorkflowDSL:publish -P mavenPassword=$pass -P mavenUser=$user $GRADLE_OPTS $ARGS1
    - gradle WorkflowCLI:publish -P mavenPassword=$pass -P mavenUser=$user $GRADLE_OPTS $ARGS1
  only:
    - dev  