apply plugin: 'java'

repositories{
    if (("true").equals(getProperty('useLocalRepo'))) {
        mavenLocal()
    }
    maven {
        credentials.username mavenUser
        credentials.password mavenPassword
        url repo
    }
    mavenCentral()
    jcenter()
}

group = "de.monticore.lang"
version = "7.5.0-SNAPSHOT"

sourceCompatibility = "11"

buildDir = "$projectDir/target"

project.ext {
    jaxbTargetDir = file("$buildDir/generated")
}

configurations {
    xsd2java
}

dependencies {
    xsd2java "com.sun.xml.bind:jaxb-xjc:3.0.2"
    xsd2java "com.sun.xml.bind:jaxb-impl:3.0.2"
    xsd2java "com.sun.xml.bind:jaxb-core:3.0.2"
    xsd2java "com.sun.activation:jakarta.activation:2.0.1"
    xsd2java "jakarta.xml.bind:jakarta.xml.bind-api:3.0.1"
    implementation "jakarta.xml.bind:jakarta.xml.bind-api:3.0.1"
}

task xsd2java() {

    doLast {
        jaxbTargetDir.mkdirs()

        ant.taskdef(name: 'xjc', classname: 'com.sun.tools.xjc.XJCTask', classpath: configurations.xsd2java.asPath)
        ant.jaxbTargetDir = jaxbTargetDir

        ant.xjc(
                destdir: '${jaxbTargetDir}',
                package: 'org.omg.spec.bpmn._20100524.model',
                schema: 'src/main/resources/BPMN20.xsd'
        )

        ant.xjc(
                destdir: '${jaxbTargetDir}',
                package: 'org.omg.spec.bpmn._20100524.model',
                schema: 'src/main/resources/BPMNDI.xsd'
        )

        ant.xjc(
                destdir: '${jaxbTargetDir}',
                package: 'org.omg.spec.bpmn._20100524.model',
                schema: 'src/main/resources/DC.xsd'
        )

        ant.xjc(
                destdir: '${jaxbTargetDir}',
                package: 'org.omg.spec.bpmn._20100524.model',
                schema: 'src/main/resources/DI.xsd'
        )

        ant.xjc(
                destdir: '${jaxbTargetDir}',
                package: 'org.omg.spec.bpmn._20100524.model',
                schema: 'src/main/resources/Semantic.xsd'
        )

    }
}

compileJava.dependsOn xsd2java

sourceSets {
    main.java.srcDirs += [jaxbTargetDir]
}