plugins {
    id 'java'
    id "com.github.johnrengelman.shadow" version "7.1.2"
    id "jacoco"
    id "de.se_rwth.codestyle" version "$mc_version"
}

group = 'de.monticore.conformance'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':WorkflowDSL')
//    implementation project(':TimerConditions')

    implementation 'org.jgrapht:jgrapht-core:1.5.2'
    implementation 'org.tinyjee.jgraphx:jgraphx:3.4.1.3'
    implementation 'org.jgrapht:jgrapht-ext:1.5.2'

    implementation project(":WorkflowDSL")
    implementation group: 'de.monticore', name: 'monticore-runtime', version: mc_version
    implementation "de.monticore:monticore-grammar:$mc_version"
    implementation "de.monticore.lang:ocl:$ocl_version"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
}

test {
    useJUnitPlatform()
}

shadowJar { // all in one jar
  manifest {
    attributes "Main-Class": "de.monticore.bpmn.conformance.BPMNConformanceTool"
  }
  archiveClassifier = 'cli'
  archiveFileName = "BPMNConformance.jar"
  zip64 = true
//        minimize()
  duplicatesStrategy DuplicatesStrategy.INCLUDE
}

tasks.register("runDemo", JavaExec) {
  classpath = files(tasks.shadowJar.archiveFile)
  def modelDir = "src/test/resources/de/monticore/workflow/conformance/caseStudy/"
  def ref = modelDir+ "PaperAuthoring.wfm"
  def conc = modelDir+ "conform/AddingNewTasks.wfm"
  args = ["-r", ref, "-c", conc]
}

tasks.register("runDemo_notconform", JavaExec) {
  classpath = files(tasks.shadowJar.archiveFile)
  def modelDir = "src/test/resources/de/monticore/workflow/conformance/caseStudy/"
  def ref = modelDir+ "PaperAuthoring.wfm"
  def conc = modelDir+ "nonconform/AntiPattern.wfm"
  args = ["-r", ref, "-c", conc]
}