plugins {
    id "java-library"
    id "com.github.johnrengelman.shadow" version "6.0.0"
    id "monticore" version "$version"
    id "jacoco"
}

group = "de.monticore.expressions"
sourceCompatibility = '11'

def grammarOutDir = "$buildDir/generated-sources/monticore/sourcecode"


sourceSets {
    main.java.srcDirs += [grammarOutDir]

    grammars {
        java.srcDirs = []
        resources {
            srcDirs([grammarDir, grammarOutDir])
            include "**/*.mc4"
        }
    }
}

configurations {grammar}

java {
    registerFeature('grammars') {
        usingSourceSet(sourceSets.grammars)
    }
}

test {
    useJUnitPlatform()
}

dependencies {
    implementation "com.google.guava:guava:$guava_version"
    implementation "joda-time:joda-time:$joda_time_version"
    implementation "com.cronutils:cron-utils:$cron_utils_version"

    /*-----------------------MONTICORE-------------------------------*/
    implementation "de.monticore:monticore-runtime:$mc_version"
    implementation "de.monticore:monticore-grammar:$mc_version"
    grammar "de.monticore:monticore-grammar:$mc_version:$grammars_classifier"

    /*------------------------TESTING-----------------------------------*/
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_jupiter_version"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:$junit_jupiter_version"
    testImplementation "de.monticore:monticore-runtime:$mc_version"
}

task generateTimeExpressions (type: MCTask) {
    grammar = file "$projectDir/$grammarDir/de/monticore/expressions/TimeExpressions.mc4"
    outputDir = file "$buildDir/generated-sources/monticore/sourcecode"
    handcodedPath "$projectDir/src/main/java"
    def uptoDate = incCheck("de/monticore/expressions/TimeExpressions.mc4")
    outputs.upToDateWhen { uptoDate }
}

compileJava.dependsOn(generateTimeExpressions)

// build sources jar in addition
task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    archiveClassifier = "sources"
}

sourcesJar.dependsOn project.collect { it.tasks.withType(MCTask)}

// build javadoc jar in addition
task javadocJar(type: Jar) {
    from javadoc
    archiveClassifier = "javadoc"
}

// generated java doc contains errors, disable for now
javadoc.failOnError(false)

// build grammar jar as well
task grammarJar(type: Jar) {
    from("$projectDir/src/main/grammars/") { include "**/*.mc4" }
    archiveClassifier = "grammars"
}


task buildAll(type: GradleBuild) {
    tasks = [ 'build' ]
}

defaultTasks 'build'

/////////////////////////   Deployment  //////////////////////////////////

// configure deployment
publishing {
    repositories.maven {
        credentials.username mavenUser
        credentials.password mavenPassword

        def releasesRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/umlp-releases/"
        def snapshotsRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/umlp-snapshots/"
        url = version.endsWith("SNAPSHOT") ? snapshotsRepoUrl : releasesRepoUrl
    }
}